- name: Install k8s and docker packages
  become: yes
  hosts: _k8s
  roles:
    - docker
    - k8s-all

- name: Setup master node
  become: yes
  hosts: _master
  roles:
    - k8s-master

- name: Setup worker node
  become: yes
  hosts: _worker
  roles:
    - k8s-worker
# Command: export KUBECONFIG=/etc/kubernetes/admin.conf
# Source:
# - https://clarusway.com/ansible-working-with-dynamic-inventory-using-aws-ec2-plugin/
# correction yml file: yamlchecker.
